import sys
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QGridLayout

class Calculator(QWidget):
    neveshte = [] 

    def __init__(self): 
        super().__init__()
        self.mohasebat = [] 
        self.layout = QGridLayout() 
        self.lbl = QLabel("Screen:") 
        self.layout.addWidget(self.lbl, 0, 0, 1, 4) 
        self.num_0 = QPushButton("0")
        self.num_0.setObjectName("0")
        self.layout.addWidget(self.num_0, 4, 2)
        self.num_1 = QPushButton("1")
        self.num_1.setObjectName("1") 
        self.layout.addWidget(self.num_1, 1, 1) 
        self.num_2 = QPushButton("2") 
        self.num_2.setObjectName("2") 
        self.layout.addWidget(self.num_2, 1, 2) 
        self.num_3 = QPushButton("3") 
        self.num_3.setObjectName("3") 
        self.layout.addWidget(self.num_3, 1, 3) 
        self.num_4 = QPushButton("4") 
        self.num_4.setObjectName("4") 
        self.layout.addWidget(self.num_4, 2, 1) 
        self.num_5 = QPushButton("5") 
        self.num_5.setObjectName("5") 
        self.layout.addWidget(self.num_5, 2, 2) 
        self.num_6 = QPushButton("6") 
        self.num_6.setObjectName("6") 
        self.layout.addWidget(self.num_6, 2, 3) 
        self.num_7 = QPushButton("7") 
        self.num_7.setObjectName("7") 
        self.layout.addWidget(self.num_7, 3, 1) 
        self.num_8 = QPushButton("8") 
        self.num_8.setObjectName("8") 
        self.layout.addWidget(self.num_8, 3, 2) 
        self.num_9 = QPushButton("9") 
        self.num_9.setObjectName("9") 
        self.layout.addWidget(self.num_9, 3, 3)
        self.hazf = QPushButton("Del") 
        self.hazf.setObjectName("Del") 
        self.plus = QPushButton("+") 
        self.plus.setObjectName("+")
        self.zarb = QPushButton("*") 
        self.zarb.setObjectName("*")
        self.tag = QPushButton("/") 
        self.tag.setObjectName("/")
        self.taf = QPushButton("-") 
        self.taf.setObjectName("-") 
        self.layout.addWidget(self.hazf, 4, 1)
        self.layout.addWidget(self.plus, 2, 4)
        self.layout.addWidget(self.zarb, 1, 4)
        self.layout.addWidget(self.taf, 3, 4)
        self.layout.addWidget(self.tag, 4, 4)
        self.mosavi = QPushButton("=") 
        self.mosavi.setObjectName("=") 
        self.layout.addWidget(self.mosavi, 4, 3) 
        self.layout.setColumnStretch(1, 60) 
        self.layout.setRowStretch(1, 1) 
        self.setLayout(self.layout) 
        self.hazf.clicked.connect(self.delete)
        self.plus.clicked.connect(self.fun)
        self.zarb.clicked.connect(self.fun)
        self.taf.clicked.connect(self.fun)
        self.tag.clicked.connect(self.fun)
        self.mosavi.clicked.connect(self.calc) 
        self.num_0.clicked.connect(self.fun)
        self.num_1.clicked.connect(self.fun) 
        self.num_2.clicked.connect(self.fun)
        self.num_3.clicked.connect(self.fun)
        self.num_4.clicked.connect(self.fun)
        self.num_5.clicked.connect(self.fun)
        self.num_6.clicked.connect(self.fun)
        self.num_7.clicked.connect(self.fun)
        self.num_8.clicked.connect(self.fun)
        self.num_9.clicked.connect(self.fun)
    def calc(self): 
        n = "".join(self.mohasebat) 
        m = eval(n) 
        self.lbl.setText(str(n) + " = " + str(m)) 
    def fun(self): 
        key = self.sender() 
        self.mohasebat.append(key.objectName()) 
        neveshte = self.mohasebat
        print(neveshte)
    def delete(self):
        self.mohasebat = []
        self.lbl.setText("Screen:")
        print("[]")

app = QApplication([]) 
window = Calculator() 
window.show() 
sys.exit(app.exec())
